# .goreleaser.yaml
version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/kest
    binary: kest
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    id: kest
    targets:
      - darwin_amd64
      - darwin_arm64
      - linux_amd64
      - linux_arm64
      - windows_amd64

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: kest
    repository:
      owner: kest-lab
      name: homebrew-kest
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/kest-lab/kest-cli"
    description: "The CLI-first API Testing Tool for Vibe Coding"
    license: "MIT"
    test: |
      system "#{bin}/kest version"
    install: |
      bin.install "kest"
