run:
  timeout: 5m
  tests: true
  build-tags: []

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - gofmt
    - goimports
    - bodyclose
    - exhaustive
    - nilerr
    - unconvert
    - unparam
    - wastedassign

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true
  
  govet:
    enable-all: true
    disable:
      - fieldalignment
  
  gofmt:
    simplify: true
  
  goimports:
    local-prefixes: github.com/zgiai/zgo
  
  misspell:
    locale: US
  
  exhaustive:
    default-signifies-exhaustive: true

issues:
  exclude-rules:
    # Exclude some linters from tests
    - path: _test\.go
      linters:
        - errcheck
        - bodyclose
    
    # Exclude test helpers
    - path: tests/
      linters:
        - errcheck
        - bodyclose
    
    # Allow TODO comments
    - source: "TODO"
      linters:
        - godox

  max-issues-per-linter: 50
  max-same-issues: 5
